#Mejorar para vínculos.
#ingestionSource = input('Nombre EXACTO del Ingestion Source')
ingestionSource = 'NETEZZA_STAGE'
prefix = 'ET'

identifier = input('id -> ')
entityNumId = input('ET... -> ')
print('\n****\n')
print('<ingestionMapping id="'+identifier+'">')
print('\t<itemTypeId>ET'+entityNumId+'</itemTypeId>')
print('\t<stagingArea xsi:type="ns2:databaseIngestionSource">')
print('\t\t<tableName>IS_Staging.E_'+(identifier.upper()).replace(" ","_")+'</tableName>')
print('\t</stagingArea>')
print('\t<dataSourceName>'+ingestionSource+'</dataSourceName>')
print('\t<securityDimensionValues>')
print('\t\t<securityDimensionValue>HI</securityDimensionValue>')
print('\t\t<securityDimensionValue>UC</securityDimensionValue>')
print('\t\t<securityDimensionValue>OSI</securityDimensionValue>')
print('\t</securityDimensionValues>')
print('\t<originId>')
print('\t\t<type>OI.'+ingestionSource+'</type>')
print('\t\t<keys>')
print('\t\t\t<key>'+ingestionSource+'</key>')
print('\t\t\t<key>'+(identifier.upper()).replace(" ","_")+'</key>')
print('\t\t\t<key>$(SOURCE_ID)</key>')
print('\t\t</keys>')
print('\t</originId>')
print('\t<createdSource>$(SOURCE_CREATED)</createdSource>')
print('\t<lastUpdatedSource>$(SOURCE_LAST_UPDATED)</lastUpdatedSource>')
print('</ingestionMapping>')
